watches =
    [
        {
            name:"REFLEX VOX DIGITAL SILICONE BLACK STRAP WATCH",
            price: 4995.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP01_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP01_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP01_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP01_4.jpg?pView=pdp",
        },
        {
            name:"REFLEX VOX DIGITAL SILICONE BLUE STRAP WATCH",
            price:4995.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP02_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP02_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP02_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP02_4.jpg?pView=pdp",
        },
        {
            name:"REFLEX VOX DIGITAL SILICONE PINK STRAP WATCH",
            price:4995.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP03_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP03_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP03_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP03_4.jpg?pView=pdp",
        },
        {
            name:"REFLEX VOX DIGITAL SILICONE RED STRAP WATCH",
            price:4995.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP04_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP04_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP04_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/38072AP04_4.jpg?pView=pdp",
        },
        {
            name:"REFLEX 3.0 DUAL TONED SMART BAND IN MIDNIGHT BLACK & BLUE ACCENT",
            price:2045.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP01A_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP01A_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP01A_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP01A_4.jpg?pView=pdp",
        },
        {
            name:"REFLEX 3.0 DUAL TONED SMART BAND IN MIDNIGHT BLACK & TURQUOISE ACCENT",
            price:2045.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP02A_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP02A_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP02A_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP02A_4.jpg?pView=pdp",
        },
        {
            name:"REFLEX 3.0 DUAL TONED SMART BAND IN MIDNIGHT BLACK & GREY ACCENT",
            price:2045.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP03A_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP03A_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP03A_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP03A_4.jpg?pView=pdp",
        },
        {
            name:"REFLEX 3.0 DUAL TONED SMART BAND IN PINK STRAP & GREEN ACCENT",
            price:2045.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP04A_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP04A_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP04A_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90067PP04A_4.jpg?pView=pdp",
        },
        {
            name:"REFLEX BEAT PURPLE SMART BAND WITH ACTIVE HEART RATE MONITOR",
            price:1865.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90066PP02_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90066PP02_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90066PP02_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/SWD90066PP02_4.jpg?pView=pdp",
        },
        {
            name:"STREETWEAR GREY DIGITAL DIAL BLACK SILICONE STRAP WATCH",
            price:1435.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/38068PP01_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/38068PP01_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/38068PP01_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/38068PP01_4.jpg?pView=pdp",
        },
        {
            name:"URBAN BOUNCE BLACK DIAL BLACK STRAP WATCH",
            price:2935.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/3268NP02_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/3268NP02_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/3268NP02_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/3268NP02_4.jpg?pView=pdp",
        },
        {
            name:"URBAN BOUNCE GREY DIAL GREY STRAP WATCH",
            price:1605.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/3265PP03_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/3265PP03_1.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/3265PP03_1.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/3265PP03_1.jpg?pView=pdp",
        },
        {
            name:"MONOCHROME GREY DIAL GREY SILICONE STRAP WATCH",
            price:715.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP01W_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP01W_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP01W_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP01W_4.jpg?pView=pdp",
        },
        {
            name:"MONOCHROME BLUE DIAL BLUE SILICONE STRAP WATCH",
            price:715.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP03W_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP03W_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP03W_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP03W_4.jpg?pView=pdp",
        },
        {
            name:"MONOCHROME PINK DIAL PINK SILICONE STRAP WATCH",
            price:715.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP05W_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP05W_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP05W_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP05W_4.jpg?pView=pdp",
        },
        {
            name:"MONOCHROME GREEN DIAL GREEN SILICONE STRAP WATCH",
            price:715.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP06W_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP06W_1.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP06W_1.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/68023PP06W_1.jpg?pView=pdp",
        },
        {
            name:"STUNNERS MULTICOLOUR DIAL BLACK METAL STRAP WATCH",
            price:1815.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/3220NM01_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/3220NM01_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/3220NM01_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/3220NM01_4.jpg?pView=pdp",
        },
        {
            name:"STUNNERS BLACK DIAL BLACK METAL STRAP WATCH",
            price:2075.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/3245NM02_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/3245NM02_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/3245NM02_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/3245NM02_4.jpg?pView=pdp",
        },
        {
            name:"STUNNERS PINK DIAL SILVER METAL STRAP WATCH",
            price:1115.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/6152SM04_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/6152SM04_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/6152SM04_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/6152SM04_4.jpg?pView=pdp",
        },
        {
            name:"COCA-COLA EDITION BY FASTRACK BLACK DIAL BLACK PLASTIC STRAP WATCH",
            price:2515.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/3260NP01_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/3260NP01_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/3260NP01_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/3260NP01_4.jpg?pView=pdp",
        },
        {
            name:"COCA-COLA EDITION BY FASTRACK BLACK DIAL GREY PLASTIC STRAP WATCH",
            price:2445.00,
            img1:"https://staticimg.titan.co.in/Fastrack/Catalog/3260SP01_1.jpg?pView=pdp",
            img2:"https://staticimg.titan.co.in/Fastrack/Catalog/3260SP01_2.jpg?pView=pdp",
            img3:"https://staticimg.titan.co.in/Fastrack/Catalog/3260SP01_3.jpg?pView=pdp",
            img4:"https://staticimg.titan.co.in/Fastrack/Catalog/3260SP01_4.jpg?pView=pdp",
        },
    ]
    localStorage.setItem("forHim", JSON.stringify(watches)); 
